/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    YourContract: {
      address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "treeId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "address",
              name: "trustedWallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "LogAllFundsSentToWallet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "contributor",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "lat",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lng",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct YourContract.LatLng",
              name: "treeId",
              type: "tuple",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "firstDepositTimestamp",
              type: "uint256",
            },
          ],
          name: "LogDeposited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "treeId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "address",
              name: "trustedWallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "LogFundsSentToWallet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "contributor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "treeId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "LogRefunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "wallet",
              type: "address",
            },
          ],
          name: "LogVaultCreated",
          type: "event",
        },
        {
          inputs: [],
          name: "DONATION_VALUE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "ONE_YEAR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          name: "depositValue",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "deposits",
          outputs: [
            {
              internalType: "address",
              name: "treeOwner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "firstDepositTimestamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "nextDisbursement",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_address",
              type: "address",
            },
          ],
          name: "getLocationList",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "treeOwner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "firstDepositTimestamp",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "nextDisbursement",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "balance",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lat",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lng",
                  type: "uint256",
                },
              ],
              internalType: "struct YourContract.TreeDeposit[]",
              name: "treeDeposits",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getONE_YEAR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          name: "getTreeDeposit",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "treeOwner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "firstDepositTimestamp",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "nextDisbursement",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "balance",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lat",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lng",
                  type: "uint256",
                },
              ],
              internalType: "struct YourContract.TreeDeposit",
              name: "treeDeposit",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          name: "getTreeId",
          outputs: [
            {
              internalType: "bytes32",
              name: "treeId",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          name: "refund",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          name: "sendFundsToWallet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "lat",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lng",
                  type: "uint256",
                },
              ],
              internalType: "struct YourContract.LatLng",
              name: "location",
              type: "tuple",
            },
          ],
          name: "setLocation",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "setLocationForTests",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "trustedWallet",
          outputs: [
            {
              internalType: "address payable",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  11155111: {
    YourContract: {
      address: "0xC3e64576aA3d4C88BC0cbe8DA1a4Ef01a302256F",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "treeId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "address",
              name: "trustedWallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "LogAllFundsSentToWallet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "contributor",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "lat",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lng",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct YourContract.LatLng",
              name: "treeId",
              type: "tuple",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "firstDepositTimestamp",
              type: "uint256",
            },
          ],
          name: "LogDeposited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "treeId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "address",
              name: "trustedWallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "LogFundsSentToWallet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "contributor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "treeId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "LogRefunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "wallet",
              type: "address",
            },
          ],
          name: "LogVaultCreated",
          type: "event",
        },
        {
          inputs: [],
          name: "DONATION_VALUE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "ONE_YEAR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          name: "depositValue",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "deposits",
          outputs: [
            {
              internalType: "address",
              name: "treeOwner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "firstDepositTimestamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "nextDisbursement",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_address",
              type: "address",
            },
          ],
          name: "getLocationList",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "treeOwner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "firstDepositTimestamp",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "nextDisbursement",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "balance",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lat",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lng",
                  type: "uint256",
                },
              ],
              internalType: "struct YourContract.TreeDeposit[]",
              name: "treeDeposits",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getONE_YEAR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          name: "getTreeDeposit",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "treeOwner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "firstDepositTimestamp",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "nextDisbursement",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "balance",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lat",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lng",
                  type: "uint256",
                },
              ],
              internalType: "struct YourContract.TreeDeposit",
              name: "treeDeposit",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          name: "getTreeId",
          outputs: [
            {
              internalType: "bytes32",
              name: "treeId",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          name: "refund",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "lat",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lng",
              type: "uint256",
            },
          ],
          name: "sendFundsToWallet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "lat",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lng",
                  type: "uint256",
                },
              ],
              internalType: "struct YourContract.LatLng",
              name: "location",
              type: "tuple",
            },
          ],
          name: "setLocation",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "setLocationForTests",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "trustedWallet",
          outputs: [
            {
              internalType: "address payable",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
